In [3]:
import pandas as pd
import numpy as np

In [89]:
df = pd.read_csv('https://www.ispdados.rj.gov.br/Arquivos/BaseDPEvolucaoMensalCisp.csv', sep= ';')
df

,cisp,mes,ano,mes_ano,aisp,risp,munic,mcirc,regiao,hom_doloso,...,cmp,cmba,ameaca,pessoas_desaparecidas,encontro_cadaver,encontro_ossada,pol_militares_mortos_serv,pol_civis_mortos_serv,registro_ocorrencias,fase
0,1,1,2003,2003m01,5,1,Rio de Janeiro,3304557,Capital,0,...,NaN,NaN,21,2,0,0,0,0,578,3
1,4,1,2003,2003m01,5,1,Rio de Janeiro,3304557,Capital,3,...,NaN,NaN,15,6,0,1,0,0,441,3
2,5,1,2003,2003m01,5,1,Rio de Janeiro,3304557,Capital,3,...,NaN,NaN,47,2,1,0,0,0,637,3
3,6,1,2003,2003m01,1,1,Rio de Janeiro,3304557,Capital,6,...,NaN,NaN,26,2,1,0,0,0,473,3
4,7,1,2003,2003m01,1,1,Rio de Janeiro,3304557,Capital,4,...,NaN,NaN,10,1,3,0,0,0,147,3
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
36898,159,10,2025,2025m10,35,4,Cachoeiras de Macacu,3300803,Interior,1,...,4.0,0.0,37,2,0,0,0,0,163,2
36899,165,10,2025,2025m10,33,5,Mangaratiba,3302601,Interior,1,...,4.0,0.0,21,0,0,0,0,0,196,2
36900,166,10,2025,2025m10,33,5,Angra dos Reis,3300100,Interior,3,...,12.0,0.0,82,8,0,1,0,0,682,2
36901,167,10,2025,2025m10,43,5,Paraty,3303807,Interior,1,...,2.0,1.0,11,1,0,0,0,0,195,2
36902,168,10,2025,2025m10,28,5,Rio Claro,3304409,Interior,0,...,0.0,0.0,3,1,0,0,0,0,66,2

In [90]:
df_furto_celular_dp = df.groupby('cisp')['furto_celular'].sum().reset_index()
df_furto_celular_dp =  df_furto_celular_dp.sort_values(by='furto_celular', ascending=False)
df_furto_celular_dp

     cisp  furto_celular
12     16          24879
2       5          23117
10     14          16945
8      12          16008
0       1          14968
..    ...            ...
87    104             72
77     92             63
131   157             55
114   138             52
129   155             47

[138 rows x 2 columns]

In [91]:
array_furto_celular_dp = np.array(df_furto_celular_dp['furto_celular'])

In [92]:
media = np.mean(array_furto_celular_dp)
mediana = np.median(array_furto_celular_dp)
q1 = np.quantile(array_furto_celular_dp, 0.25)
q2 = np.quantile(array_furto_celular_dp, 0.50)
q3 = np.quantile(array_furto_celular_dp, 0.75)
#Distância = (média - mediana) / mediana
distancia = ((media - mediana)/mediana)
distanciaDEC = (distancia)*100
iqr = q3 - q1
limite_superior = q3 + 1.5 * iqr
limite_inferior = q1 - 1.5 * iqr

 
print("A média é " +str(media))
print(f'A mediana é {mediana}')
print(f'Primeiro quartil (Q1): {q1}')
print(f'Segundo quartil (Q2, Mediana): {q2}')
print(f'Terceiro quartil (Q3): {q3}')
#Distância = (média - mediana) / mediana
distancia = ((media - mediana)/mediana)
distanciaDEC = (distancia)*100
print(f"A distância é {distanciaDEC}") 
print(f'O IQR é {iqr}')
print(f'O limite superior é {limite_superior}')
print(f'O limite inferior é {limite_inferior}')

A média é 3338.1159420289855
A mediana é 1633.5
Primeiro quartil (Q1): 449.0
Segundo quartil (Q2, Mediana): 1633.5
Terceiro quartil (Q3): 4498.25
A distância é 104.35359302289473
O IQR é 4049.25
O limite superior é 10572.125
O limite inferior é -5624.875

In [93]:
outliers_furto_celular_dp = df_furto_celular_dp.loc[(df_furto_celular_dp['furto_celular'] > limite_superior) | (df_furto_celular_dp['furto_celular'] < limite_inferior)]
outliers_furto_celular_dp

    cisp  furto_celular
12    16          24879
2      5          23117
10    14          16945
8     12          16008
0      1          14968
5      9          14159
6     10          14105
1      4          13318
14    18          12939
28    32          12206
31    35          11824

In [94]:
df_estelionato_dp = df.groupby('munic')['estelionato'].sum().reset_index()
df_estelionato_dp =  df_estelionato_dp.sort_values(by='estelionato', ascending=False)
df_estelionato_dp

                                                munic  estelionato
68                                     Rio de Janeiro       606042
48                                            Niterói        50603
23                                    Duque de Caxias        41281
78                                        São Gonçalo        37222
50                                        Nova Iguaçu        36742
..                                                ...          ...
35                                     Laje do Muriaé          173
83                              São Sebastião do Alto          138
61                                   Queimados;Japeri           50
57                                    Piraí;Pinheiral            8
14  Campos dos Goytacazes;São Francisco de Itabapoana            7

[90 rows x 2 columns]

In [95]:
array_estelionato_dp = np.array(df_estelionato_dp['estelionato'])

In [96]:
media = np.mean(array_estelionato_dp)
mediana = np.median(array_estelionato_dp)
q1 = np.quantile(array_estelionato_dp, 0.25)
q2 = np.quantile(array_estelionato_dp, 0.50)
q3 = np.quantile(array_estelionato_dp, 0.75)

print("A média é " +str(media))
print(f'A mediana é {mediana}')
print(f'Primeiro quartil (Q1): {q1}')
print(f'Segundo quartil (Q2, Mediana): {q2}')
print(f'Terceiro quartil (Q3): {q3}')
#Distância = (média - mediana) / mediana
distancia = ((media - mediana)/mediana)
distanciaDEC = (distancia)*100
print(f"A distância é {distanciaDEC}")

A média é 12167.655555555555
A mediana é 1472.0
Primeiro quartil (Q1): 639.5
Segundo quartil (Q2, Mediana): 1472.0
Terceiro quartil (Q3): 7197.5
A distância é 726.6070350241546

In [97]:
munic_acima_q3 = df_estelionato_dp.loc[df_estelionato_dp['estelionato'] > q3]
munic_acima_q3

                    munic  estelionato
68         Rio de Janeiro       606042
48                Niterói        50603
23        Duque de Caxias        41281
78            São Gonçalo        37222
50            Nova Iguaçu        36742
81     São João de Meriti        23172
13  Campos dos Goytacazes        22142
54             Petrópolis        17251
36                  Macaé        16577
89          Volta Redonda        16050
6            Belford Roxo        15785
9               Cabo Frio        11407
49          Nova Friburgo        11041
67         Rio das Ostras        10728
85            Teresópolis        10237
47              Nilópolis         9967
41                 Maricá         9928
63                Resende         8359
38                   Magé         8335
0          Angra dos Reis         8208
1                Araruama         8019
27               Itaboraí         8001
43               Mesquita         7443

In [98]:
munic_acima_q1 = df_estelionato_dp.loc[df_estelionato_dp['estelionato'] < q1]
munic_acima_q1

                                                munic  estelionato
17                                              Carmo          637
39                                    Magé;Guapimirim          624
20                                Conceição de Macabú          622
74                                       Silva Jardim          621
46                               Natividade;Varre-Sai          547
58                                        Porciúncula          517
71                                           Sapucaia          517
79                      São José do Vale do Rio Preto          468
65                                          Rio Claro          462
16                             Cardoso Moreira;Italva          443
24                        Engenheiro Paulo de Frontin          379
12                                            Cambuci          370
22                                        Duas Barras          352
32   Itaperuna;São José de Ubá;Cardoso Moreira;Italva          328
75                                          Sumidouro          324
66                                     Rio das Flores          271
69                               Santa Maria Madalena          230
86                                  Trajano de Morais          176
35                                     Laje do Muriaé          173
83                              São Sebastião do Alto          138
61                                   Queimados;Japeri           50
57                                    Piraí;Pinheiral            8
14  Campos dos Goytacazes;São Francisco de Itabapoana            7

In [99]:
#o Secretário quer identificar aqueles que menos tiveram. A mesma análise deve ser feita verificando dados de apreensão de menores.
df_aaapai_dp = df.groupby('munic')['aaapai'].sum().reset_index()
df_aaapai_dp =  df_aaapai_dp.sort_values(by='aaapai', ascending=False)
df_aaapai_dp

                                                munic   aaapai
68                                     Rio de Janeiro  48246.0
78                                        São Gonçalo   7176.0
23                                    Duque de Caxias   6244.0
13                              Campos dos Goytacazes   5468.0
48                                            Niterói   5316.0
..                                                ...      ...
75                                          Sumidouro     13.0
66                                     Rio das Flores     12.0
14  Campos dos Goytacazes;São Francisco de Itabapoana      0.0
57                                    Piraí;Pinheiral      0.0
61                                   Queimados;Japeri      0.0

[90 rows x 2 columns]

In [100]:
array_aaapai_dp = np.array(df_aaapai_dp['aaapai'])

In [101]:
media = np.mean(array_aaapai_dp)
mediana = np.median(array_aaapai_dp)
q1 = np.quantile(array_aaapai_dp, 0.25)
q2 = np.quantile(array_aaapai_dp, 0.50)
q3 = np.quantile(array_aaapai_dp, 0.75)

print("A média é " +str(media))
print(f'A mediana é {mediana}')
print(f'Primeiro quartil (Q1): {q1}')
print(f'Segundo quartil (Q2, Mediana): {q2}')
print(f'Terceiro quartil (Q3): {q3}')
#Distância = (média - mediana) / mediana
distancia = ((media - mediana)/mediana)
distanciaDEC = (distancia)*100
print(f"A distância é {distanciaDEC}")

A média é 1353.2444444444445
A mediana é 297.5
Primeiro quartil (Q1): 86.0
Segundo quartil (Q2, Mediana): 297.5
Terceiro quartil (Q3): 934.25
A distância é 354.87208216619985

In [102]:
munic_acima_q3 = df_aaapai_dp.loc[df_aaapai_dp['aaapai'] > q3]
munic_acima_q3

                                        munic   aaapai
68                             Rio de Janeiro  48246.0
78                                São Gonçalo   7176.0
23                            Duque de Caxias   6244.0
13                      Campos dos Goytacazes   5468.0
48                                    Niterói   5316.0
50                                Nova Iguaçu   4115.0
9                                   Cabo Frio   3111.0
81                         São João de Meriti   2965.0
6                                Belford Roxo   2605.0
89                              Volta Redonda   2210.0
49                              Nova Friburgo   2106.0
54                                 Petrópolis   1935.0
36                                      Macaé   1851.0
27                                   Itaboraí   1742.0
85                                Teresópolis   1572.0
63                                    Resende   1569.0
67                             Rio das Ostras   1434.0
38                                       Magé   1261.0
43                                   Mesquita   1220.0
4                                 Barra Mansa   1175.0
0                              Angra dos Reis   1112.0
82                        São Pedro da Aldeia    957.0
19  Comendador Levy Gasparian;Areal;Três Rios    942.0

In [103]:
#Qual delegacia destoa  das demais no que diz  respeito a ocorrências relacionadas à furto e roubo de veículos na capital ?


df_capital = df.loc[df['munic'] == "Rio de Janeiro"]
df_capital['veiculo'] = df_capital['furto_veiculos'] + df_capital['roubo_veiculo']

C:\Users\anne.souza\AppData\Local\Temp\ipykernel_71644\3163839651.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_capital['veiculo'] = df_capital['furto_veiculos'] + df_capital['roubo_veiculo']

In [109]:
df_veiculo_capital = df_capital.groupby('cisp')['veiculo'].sum().reset_index()
df_veiculo_capital =  df_veiculo_capital.sort_values(by='veiculo', ascending=False)
df_veiculo_capital

    cisp  veiculo
23    27    39024
30    34    36897
31    35    33436
35    39    32500
34    38    25999
29    33    25899
17    21    25267
18    22    22896
36    40    22451
25    29    21722
12    16    18151
26    30    17822
27    31    17650
40    44    17163
19    23    15245
20    24    14626
24    28    14437
28    32    13884
16    20    13238
33    37    12938
5      9    12705
21    25    12697
13    17    11250
14    18    11239
22    26    10398
15    19    10180
37    41    10175
38    42    10108
32    36    10077
6     10     9669
3      6     6777
39    43     4428
2      5     4343
4      7     3941
10    14     3506
1      4     3402
11    15     3083
0      1     2494
8     12     2408
9     13     1488
7     11      181
41    45       78

In [110]:
#Na última década, algum município da região metropolitana pode ser considerado outlier sobre as ocorrências de furto de veículos?
array_df_veiculo_capital = np.array(df_veiculo_capital['veiculo'])

In [112]:
media = np.mean(array_df_veiculo_capital)
mediana = np.median(array_df_veiculo_capital)
q1 = np.quantile(array_df_veiculo_capital, 0.25)
q2 = np.quantile(array_df_veiculo_capital, 0.50)
q3 = np.quantile(array_df_veiculo_capital, 0.75)
#Distância = (média - mediana) / mediana
distancia = ((media - mediana)/mediana)
distanciaDEC = (distancia)*100
iqr = q3 - q1
limite_superior = q3 + 1.5 * iqr
limite_inferior = q1 - 1.5 * iqr

 
print("A média é " +str(media))
print(f'A mediana é {mediana}')
print(f'Primeiro quartil (Q1): {q1}')
print(f'Segundo quartil (Q2, Mediana): {q2}')
print(f'Terceiro quartil (Q3): {q3}')
#Distância = (média - mediana) / mediana
distancia = ((media - mediana)/mediana)
distanciaDEC = (distancia)*100
print(f"A distância é {distanciaDEC}") 
print(f'O IQR é {iqr}')
print(f'O limite superior é {limite_superior}')
print(f'O limite inferior é {limite_inferior}')

A média é 13949.333333333334
A mediana é 12701.0
Primeiro quartil (Q1): 5015.25
Segundo quartil (Q2, Mediana): 12701.0
Terceiro quartil (Q3): 18068.75
A distância é 9.8286224181823
O IQR é 13053.5
O limite superior é 37649.0
O limite inferior é -14565.0

In [113]:
outliers_df_veiculo_capital = df_veiculo_capital.loc[(df_veiculo_capital['veiculo'] > limite_superior) | (df_veiculo_capital['veiculo'] < limite_inferior)]
outliers_df_veiculo_capital

    cisp  veiculo
23    27    39024

In [14]:

import pandas as pd
import numpy as np

url = "https://www.ispdados.rj.gov.br/Arquivos/BaseMunicipiomensal.csv"
df = pd.read_csv(url, sep=";", encoding="latin1")

# Normalizar nomes das colunas (minúsculas, sem espaços nas pontas)
df.columns = [c.strip().lower() for c in df.columns]

# Conferir rapidamente
print("Colunas:", df.columns.tolist())
df.head(3)

Colunas: ['fmun_cod', 'fmun', 'ano', 'mes', 'mes_ano', 'regiao', 'hom_doloso', 'lesao_corp_morte', 'latrocinio', 'cvli', 'hom_por_interv_policial', 'letalidade_violenta', 'tentat_hom', 'lesao_corp_dolosa', 'estupro', 'hom_culposo', 'lesao_corp_culposa', 'roubo_transeunte', 'roubo_celular', 'roubo_em_coletivo', 'roubo_rua', 'roubo_veiculo', 'roubo_carga', 'roubo_comercio', 'roubo_residencia', 'roubo_banco', 'roubo_cx_eletronico', 'roubo_conducao_saque', 'roubo_apos_saque', 'roubo_bicicleta', 'outros_roubos', 'total_roubos', 'furto_veiculos', 'furto_transeunte', 'furto_coletivo', 'furto_celular', 'furto_bicicleta', 'outros_furtos', 'total_furtos', 'sequestro', 'extorsao', 'sequestro_relampago', 'estelionato', 'apreensao_drogas', 'posse_drogas', 'trafico_drogas', 'apreensao_drogas_sem_autor', 'recuperacao_veiculos', 'apf', 'aaapai', 'cmp', 'cmba', 'ameaca', 'pessoas_desaparecidas', 'encontro_cadaver', 'encontro_ossada', 'pol_militares_mortos_serv', 'pol_civis_mortos_serv', 'registro_ocorrencias', 'fase']

,fmun_cod,fmun,ano,mes,mes_ano,regiao,hom_doloso,lesao_corp_morte,latrocinio,cvli,...,cmp,cmba,ameaca,pessoas_desaparecidas,encontro_cadaver,encontro_ossada,pol_militares_mortos_serv,pol_civis_mortos_serv,registro_ocorrencias,fase
0,3300100,Angra dos Reis,2014,1,2014m01,Interior,11,0,0,11,...,8,0,98,13,3,0,0,0,561,3
1,3300159,Aperibé,2014,1,2014m01,Interior,0,0,0,0,...,0,0,0,0,0,0,0,0,0,3
2,3300209,Araruama,2014,1,2014m01,Interior,2,0,0,2,...,5,0,91,10,1,0,0,0,480,3

In [15]:
print(df[["fmun", "mes"]].head())

                 fmun  mes
0      Angra dos Reis    1
1             Aperibé    1
2            Araruama    1
3               Areal    1
4  Armação dos Búzios    1